# Generated by Django 5.0.6 on 2024-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=10)),
                ('account_email', models.EmailField(max_length=254)),
                ('account_order', models.DateField()),
            ],
        ),
    ]
