# Generated by Django 5.0.6 on 2024-08-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_taskstatus_music_name_taskstatus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=255)),
                ('bpm', models.IntegerField()),
                ('segments', models.JSONField()),
            ],
        ),
    ]
