# Generated by Django 5.0.6 on 2024-08-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_audioanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
