# Generated by Django 5.0.6 on 2024-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_taskstatus_bpm_taskstatus_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
