# Generated by Django 5.0.6 on 2024-12-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_taskstatus_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='segments',
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='task_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start', models.FloatField()),
                ('duration', models.FloatField()),
                ('end', models.FloatField()),
                ('color', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=50)),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='upload.taskstatus')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('task_status', 'order')},
            },
        ),
    ]
