# Generated by Django 5.0.6 on 2024-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_remove_taskstatus_id_remove_taskstatus_segments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='bpm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='segment',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start',
            field=models.FloatField(default=0),
        ),
    ]
