# Generated by Django 5.0.6 on 2024-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_segment_bpm_alter_segment_duration_alter_segment_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='sketch',
            field=models.CharField(default='', max_length=255),
        ),
    ]
