# Generated by Django 5.0.6 on 2024-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_segment_sketch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='segment',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='segment',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
