# Generated by Django 5.0.6 on 2024-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_alter_segment_color_alter_segment_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='color',
            field=models.JSONField(),
        ),
    ]
