# Generated by Django 5.0.6 on 2024-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_alter_taskstatus_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='music_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
