# Generated by Django 5.0.6 on 2024-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_taskstatus_music_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='music_url_web',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
